### ISSUE TITLE
Formulaire sourcing des artistes

### ISSUE THREAD

**Issue by JulieADA** [ClementADA/ADA#114]
https://www.book.fr/register?trk=m&ref=121380&utm_expid=6861644-4.ijIFKeX_S8CNEcbsnlwZZg.0&utm_referrer=http%3A%2F%2Fwww.sofi.book.fr%2Fcontact%2F

**Comment by ClementADA** [comment]
https://artsdesignafrica.com/inscription-artistes/ ca vous va ?
