### ISSUE TITLE
Paiement CB en attente

### ISSUE THREAD

**Issue by JustineADA** [ClementADA/ADA#117]
Est-il possible de faire ca ?

Après vérification de la disponibilité de l’œuvre auprès de l’artiste, nous vous enverrons un mail de confirmation dans les plus brefs délais. Si l’œuvre est bien disponible, vous serez alors débité. Dans le cas contraire, si l’œuvre est indisponible, rien ne vous sera débité.

**Comment by ClementADA** [comment]
ATTENTION C'est FAIT MERCI DE LIRE TRÈS TRÈS TRÈS ATTENTIVEMENT CE MESSAGE :
les commandes en CB ne sont plus débiter automatiquement. Il faudra manuellement valider la commande sous 7 jours MAXIMUM sinon après la commande sera annulé.

Whether or not to immediately capture the charge. When unchecked, the charge issues an authorization and will need to be captured later. Uncaptured charges expire in 7 days.

**Comment by ClementADA** [comment]
Pour Paypal c'est un autorisation il faudra aussi valider manuellement
