### ISSUE TITLE
Onglet des pages Tableaux

### ISSUE THREAD

**Issue by JustineADA** [ClementADA/ADA#120]
Inverser les onglets sur les informations sur la page des tableaux.
Il faut voir en priorité les informations techniques
et ensuite le texte des oeuvres

**Comment by ClementADA** [comment]
Function.php (theme)

add_filter( 'woocommerce_product_tabs', 'woo_reorder_tabs', 98 );
function woo_reorder_tabs( $tabs ) {

	$tabs['additional_information']['priority'] = 5;	// Additional information third	
	$tabs['description']['priority'] = 10;			// Description second
	$tabs['reviews']['priority'] = 15;			// Reviews first

	return $tabs;
}
