### ISSUE TITLE
Slide Réseaux sociaux - Pitch

### ISSUE THREAD

**Issue by JustineADA** [ClementADA/ADA#153]
une slide qui pourrait etre ajouter dans notre pitch pour montrer notre engagement sur nos reseaux sociaux (les donnees cles a presenter).
Tu parlais de notre bon taux d'engagement, il faudrait le mettre en avant.
Je te laisse carte blanche pour les metrics à choisir

**Comment by ClementADA** [comment]
Il me faudrait les accès Twitter et Insta

**Comment by JustineADA** [comment]
Tu peux les demander à Julie. C'est elle qui les gère

**Comment by ClementADA** [comment]
Twitter : https://twitter.com/ArtsDesign_54
abissegue2002@yahoo.fr
Mot de Passe : Mossane1971?


Instagram : 
https://www.instagram.com/artsdesignafrica/?hl=fr
Mot de Passe : Mossane1971?
