### ISSUE TITLE
Faire le point sur les contrats

### ISSUE THREAD

**Issue by JustineADA** [ClementADA/ADA#181]
Julie, peux tu noter, ceux que tu as reçu par la poste :

**Comment by JulieADA** [comment]
Faire un  point contrat @JustineADA  - Galerie ADA : Point 30 juin 2017 - 
Manque Bill

**Comment by JustineADA** [comment]
Les artistes & Designers :
- Joe => OK
- Yao  => OK
- Fred  => OK
- Fawzi  => OK
- Anissa  => OK
- Weymidesign  => OK
- Patricia Flavien  => OK
- Henri Abraham Univers => OK
- Ange & Dam => OK
- Setou => OK
- Arlet Johnson => OK

- Maison Malou
- Aza Mansongi
- Bill Akwa Betote => Relancé 27/06
- Mario  => Relancé 27/06

**Comment by JustineADA** [comment]
Julie,
Peux tu scanner les contrats suivants et le enregistrer dans le drive, dans les dossiers de chaque artistes ?
Joe => OK
Yao => OK
Fred => OK
Fawzi => OK

**Comment by JulieADA** [comment]
Julie scanner les contrats - ADA  4 
Joe => OK

Yao => OK

Fred => OK

Fawzi => OK
