### ISSUE TITLE
Site - mise en avant des dimensions

### ISSUE THREAD

**Issue by JustineADA** [ClementADA/ADA#214]
Sur les pages oeuvres :
- L'onglet description est à nouveau affiché en premier, alors que les dimensions et techniques devraient l'etre.

Pour résoudre le problème, faire 2 paragraphes, à la suite l'un de l'autre.

**Comment by ClementADA** [comment]
J'ai remis dans l'order par contre je ne peux pas mettre l'un en dessous de l'autre
