### ISSUE TITLE
Site Web

### ISSUE THREAD

**Issue by JulieADA** [ClementADA/ADA#41]
mes remarques général sur le site 
il nous faut une landing page : qui explique rapidement au visiteur où il est : http://littleafrica.fr/  cf : Leur landing page

Sur la typo plus grasse  et le manque d’identité africaine de la galerie : http://littleafrica.fr/city-guide-afrique-paris/artistes/:

https://artsdesignafrica.com/home-0/
https://artsdesignafrica.com/les-artistes
https://artsdesignafrica.com/galerie
https://artsdesignafrica.com/mode-is-art/

**Comment by ClementADA** [comment]
Dans ce cas merci de proposer sous forme de schema la landing que vous voulez
