### ISSUE TITLE
Inscription CNIL ?

### ISSUE THREAD

**Issue by JustineADA** [ClementADA/ADA#43]
Faut-il s'y inscrire ? Les cookies vont etre activés ?

**Comment by ClementADA** [comment]
Oui. Mais il faut le siret :
Deux fichiers à remplir NS048 (donnée client), NS018 Traitement statistique,

**Comment by ClementADA** [comment]
done

**Comment by JustineADA** [comment]
Vie privee dans mentions legales

**Comment by JustineADA** [comment]
https://www.cnil.fr/fr/exemple-de-bandeau-cookie

Il est obligatoire de prevenir l'utilisateur. As tu fait le bandeau le CNIl donne un exemple.
