### ISSUE TITLE
Google Translate

### ISSUE THREAD

**Issue by JulieADA** [ClementADA/ADA#79]
google translate api free / étudier pour le lancement

**Comment by ClementADA** [comment]
Installé, cependant j'émet une réserve. En effet vos utilisateurs à l'étranger ne trouverons pas votre site via Google (sauf bouche à oreille), cela ne référence pas votre site à l'étranger. C'est une aide à la lecture pour ceux qui ne parle pas français. 
En terme de stratégie ce n'est pas une bonne idée, car il n'y a aucun intérêt. Les personnes allant sur des sites étranger sont habituer à avoir un traducteur intégré.
