### ISSUE TITLE
Pop up newsletter

### ISSUE THREAD

**Issue by JustineADA** [ClementADA/ADA#83]
La fenetre popo-up de newslettre s'ouvre plusieurs fois apres l'avoir fermé.

**Comment by ClementADA** [comment]
Les joies des popups mais je vais voir ce que je peux faire. je passe en back log car pas prioritaire

**Comment by ClementADA** [comment]
Le plugin bug à cause des autres systèmes. Il a fait planté WP je l'ai supprimé
