### ISSUE TITLE
MIA - Yao

### ISSUE THREAD

**Issue by JustineADA** [ClementADA/ADA#91]
TOutes les oeuvres de Yao sont mélangées. Il faut les séparer. Pour n'avoir que celles de MIA

**Comment by ClementADA** [comment]
Dans ce cas il faut faire une page spécial pour YAO pour MIA et il faut utiliser le widget products en créant une nouvelle page :) Je vous formerai à cela vendredi

**Comment by JustineADA** [comment]
Ok oui je veux bien ! Merci
