### ISSUE TITLE
MIA - Expedition impossible

### ISSUE THREAD

**Issue by JustineADA** [ClementADA/ADA#92]
Changer le texte automatique pour nous dire de nous contacter via le formulaire. Plutot que cette phrase : 
"Il n’y a aucune méthode de livraison disponible. Veuillez vérifier votre adresse ou contactez-nous si vous avez besoin d’aide."

**Comment by ClementADA** [comment]
Je ne comprends pas. Tu peux me dire sur quelle URL?

**Comment by JustineADA** [comment]
https://artsdesignafrica.com/produit/le-gardien-yao-metsoko/
EN fait les dimensions sont immenses. DU coup normal, les transporteurs classiques ne peuvent pas s'en charger. il faudra faire un devis avec une boite spécialisée.
J'aurais juste voulu changer le texte automatique de envoi moins cher
